### ISSUE TITLE
List of TODO's

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/ANANSE#2]
Let's keep a list of things that still need to be done, I'll update this when I come across more issues. 

- [x] Remove all irrelevant data from the `data/` directory.
- [x] Add two example files, for instance for fibroblasts and keratinocytes, to be able to test the method.
- [x] Create a main script `ananse` with several subcommands (`binding`, `grn` and `influence`).
- [x] Make sure the input is not size-specific. If the regions are larger than 200bp they should be resized to 200 bp.
